### ISSUE TITLE
Optimization: skip parsing UASTs for file@revision, if they were already parsed

### ISSUE THREAD

**Issue by bzz** [src-d/berserker#19]
Right now we parse UAST for every file/commitHash (of HEAD ref) of each non-rooted repo, but this has a lot of overhead i.e in case of forks. 

As files are guaranteed not to change for the same commitHash, which is something we take advantage of on the storage layer, why not to take advantage of the same knowlege in processing part?

One design of such cache could be: an instance of Memcache (with appropriate eviction policy for fixed RAM capacity) for storing the fact that UAST was extracted for `fileName/commitHash`, so we could skip those on in berserker's Golang part.

It's simple to deploy and use, which guarantees that while implementing we save some time, to spend on performance implications measurement :)

**Comment by smola** [comment]
Actually, at this point we can just process one HEAD per rooted repository. That would mean ignoring forks and the duplication problem would be only with vendored files, which is a much lower proportion.

**Comment by bzz** [comment]
Good point. But would not that imply changing the way we iterate over dataset as well?

So far, in Berserker we
 1.  fetch all original RepoIDs though JDBC in Spark job.
 2. repartition them, so each Task in Spark gets the subset of IDs
 3. for each partition: Golang, which iterate over batch of RepoIDs, for each RepoID/ref
 4. open rootedRepo 
 5. extract a tree from HEAD for the ref to original repo history
 6. for each file in that tree - emit data back to Task though gRPC

Looks like a commit cache seems less invasive and would not require any changes, except for 
 - one more check in 5 (even checking hashes for full dirs should be possible)
 - `kubectl create ...`

**Comment by smola** [comment]
:+1:
See this: https://github.com/src-d/berserker/issues/20

**Comment by bzz** [comment]
Closing this as, as noted, we pushed similar idea further in #20
