### ISSUE TITLE
Remove local build of dependecies, as soon as they are published

### ISSUE THREAD

**Issue by bzz** [src-d/berserker#30]
As soon as 

 - [x] https://github.com/bzz/client-scala is published on jitpack 
         `com.github.bzz:client-scala:390362d7dc`
 - [ ] https://github.com/src-d/siva-java/issues/5 resolved and 
        `tech.sourced:siva-java_2.11:0.1.0-SNAPSHOT` published on jitpack
 - [ ] https://github.com/src-d/backlog/issues/973#issuecomment-323255955 resolved and
        `tech.sourced:enry-java:1.0,tech.sourced:siva-java_2.11:0.1.0-SNAPSHOT` published on jitpack

Do:

 - remove `./local-install-*.sh`
 - update `.travis.yml`
 - update README

**Comment by smola** [comment]
Low priority after https://github.com/src-d/berserker/pull/33

**Comment by bzz** [comment]
Scope updated to include all deps
