### ISSUE TITLE
Add Travis integration

### ISSUE THREAD

**Issue by ajnavarro** [src-d/berserker#4]
It would be nice to have TravisCI 
 - starting `bblfsh server`
 - running build for both Golang & Scala
 - running `./test` from #16 
 - badge in README

As we do not use a common build system as https://bazel.build/ - it should be possible to have a common `./package`, `./test` shell wrappers in root dir that are called by Travis

**Comment by bzz** [comment]
Updated the description

**Comment by bzz** [comment]
Closing as initial work was done in #20 and more improvements are expected to be added under #16
